version: 2
updates:
  # GitHub Actions updates
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - "dependencies"
      - "skip-release"
    commit-message:
      prefix: "ci"
      include: "scope"

  # npm dependencies updates  
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    labels:
      - "dependencies"
      - "skip-release"
    commit-message:
      prefix: "deps"
      include: "scope"
    ignore:
      # Ignore major version updates for peer dependencies
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-dom"  
        update-types: ["version-update:semver-major"]