coverage:
  precision: 2
  round: down
  range: 70..90

  status:
    project:
      default:
        target: 80%
        threshold: 1%
        informational: false
    patch:
      default:
        target: 80%
        threshold: 0%
        informational: false