blank_issues_enabled: false
contact_links:
  - name: 📖 Documentation
    url: https://github.com/Santyzz0311/useful-react-hooks#readme
    about: Check the README for usage examples and API reference
  - name: 💬 Discussions
    url: https://github.com/Santyzz0311/useful-react-hooks/discussions
    about: Ask questions and discuss ideas with the community
  - name: 📦 NPM Package
    url: https://www.npmjs.com/package/iuseful-react-hooks
    about: View the published package on NPM
